### ISSUE TITLE
Add a credits or contributors page

### ISSUE THREAD

**Issue by n-kall** [n-kall/priorDB#15]
There should be a clear indication of who has contributed to the database. Perhaps even on each prior page

**Comment by aloctavodia** [comment]
GitHub already has a contribution page, so we can just link to that. Or use some automatic routine to keep an up-to-date list with some custom formating.

Not oposed to have attribution per page, but a global contribution could be enough and easier to maintaining, assuming in the future many people could contribute to a single page.

**Comment by aloctavodia** [comment]
I just noticed that your contributions are not listed . This are some commons reasons for that and possible fixes. https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-profile/managing-contribution-settings-on-your-profile/why-are-my-contributions-not-showing-up-on-my-profile

**Comment by aloctavodia** [comment]
Do you want something like this https://github.com/marketplace/actions/contribute-list or the GitHub contribution graph is enough?

**Comment by n-kall** [comment]
I think it would be good to display contributors on the rendered webpage somehow, not just on github. If we can adjust this contribute-list to do that, it would be great
