### ISSUE TITLE
Alternative Beta model/description 

### ISSUE THREAD

**Issue by aloctavodia** [n-kall/priorDB#3]
Here https://github.com/n-kall/priorDB/blob/master/gen_linear_regression/beta.qmd Beta regression is discussed in terms of alfa and beta parametrization, but there are alternatives like mu (mean) and nu (concentration), with mu as a function of the covariates and nu as an "auxiliary" parameter.

**Comment by aloctavodia** [comment]
I was thinking about something like this:

\begin{align}
y_i \sim \text{beta}(mu=\text{logit}^{-1}(\mu_i), \nu=\nu) \\
\mu_i = \alpha_{\mu} + \beta_{\mu} \cdot x \\
\nu=  \text{some positive distribution}\\
\end{align}

In PyMC/Preliz the concentration parameter name is $\nu$ and in Stan is $\kappa$.

**Comment by n-kall** [comment]
Now I see what you mean. We could remove the coefficients for the precision term, and make it just an auxiliary parameter. That makes more sense. I can make this change tomorrow, or you can change it

**Comment by aloctavodia** [comment]
Sure, I can work on this.
